### ISSUE TITLE
Crunchbase::Organization.find_all_by_query breaks if company name includes ampersand

### ISSUE THREAD

**Issue by russorat** [sandisk/crunchbase-api#4]
Looks like the find_all_by_query function does not correctly handle the ampersand (&) symbol when encoding the url. Maybe try CGI::escape() instead of URI::escape() [here](https://github.com/sandisk/crunchbase-api/blob/master/lib/crunchbase-api.rb#L30)?

```ruby
Crunchbase::Organization.find_all_by_query('Ernst & Young LLP').first
Crunchbase::CrunchbaseException: Failed to fetch https://api.crunchbase.com/v/2/organizations?query=Ernst%20&%20Young%20LLP&page=1&order=created_at%20desc&user_key=xxxxxxxxxxxxxx: Bad Encoding
	from /var/lib/gems/1.9.1/gems/crunchbase-api-0.2.1/lib/crunchbase-api.rb:41:in `rescue in fetch'
	from /var/lib/gems/1.9.1/gems/crunchbase-api-0.2.1/lib/crunchbase-api.rb:32:in `fetch'
	from /var/lib/gems/1.9.1/gems/crunchbase-api-0.2.1/lib/crunchbase-api/entity.rb:20:in `fetch_list'
	from /var/lib/gems/1.9.1/gems/crunchbase-api-0.2.1/lib/crunchbase-api/organization.rb:62:in `find_all_by_query'
	from (irb):20
	from /usr/bin/irb:12:in `<main>'
```

**Comment by russorat** [comment]
https://github.com/sandisk/crunchbase-api/pull/5

**Comment by sandisk** [comment]
Closing this. Cheers!
